zzgh06/cooking-recipe-fe

src/pages/MainPage.js

ex) 제목(새로운 기능을 추가했다 혹은 버그 해결)
- 회원가입 기능 추가 등의 상세내용을 적어주시면 됩니다.

Git Collaboration Practice

---

package-lock.json
package.json
public/index.html
src/component/Footer.js
src/pages/AdminOrderPage.js
src/pages/AdminProduct.js
src/pages/AdminUserPage.js
src/pages/CartPage.js
src/pages/Ingredients.js
src/pages/LoginPage.js
src/pages/MyFridge.js
src/pages/MyPage.js
src/pages/MyProfile.js
src/pages/OrderCompletePage.js
src/pages/PaymentPage.js
src/pages/RecipeDetail.js
src/pages/RegisterPage.js
src/router/AppRouter.js
src/router/PrivateRoute.js
src/utils/api.js

I add AppRouter with private routes for customer and admin

page-config

---

src/component/User/userComponent.js
src/pages/LoginPage.js

fix loginPage
update Id to email

fix id to email

---

src/component/Footer/Footer.style.css
src/component/Navbar/Navbar.style.css

Design Navbar and tooter style change
- 네브바와 푸터 스타일 변경

Design Navbar and tooter style change

---

src/component/Navbar/Dropdown.js
src/component/Navbar/Navbar.js
src/component/Navbar/Navbar.style.css

Design Separate dropdown component from Navbar
- 기존의 네브바 컴포넌트에 있던 드랍다운을 분리시켜 컴포넌트화

Design Separate dropdown component from Navbar

---

src/component/Footer/Footer.style.css
src/component/Navbar/Navbar.style.css

Fix navbar and footer layout modify
- 네브바 및 푸터 레이아웃 수정

Fix navbar and footer layout modify

---

package-lock.json
package.json
src/component/Banner/BannerComponent.js
src/component/Banner/BannerComponent.style.css
src/component/Navbar/Navbar.js
src/component/Navbar/Navbar.style.css
src/pages/MainPage.js

Design Banner component And Fix Navbar style css modify
- 배너 컴포넌트 추가
- 배너 컴포넌트를 위해 react-multi-crousel npm module 설치
- Navbar style css 변경

Design Banner component And Fix Navbar style css modify

---

src/component/IngredientCard/IngredientCard.js
src/component/IngredientCard/IngredientCard.style.css

Design ingredient card
- ingredient card 컴포넌트 추가

Design ingredient card

---

src/App.css
src/Layout/AppLayout.js
src/component/Navbar/Navbar.js
src/component/Navbar/Navbar.style.css
src/pages/LoginPage.js

Router change and Navbar style change according to user level
- 유저 레벨에 따라 어드민 페이지로 이동할 수 있는 ui 추가
- Navbar style 조정

Router change and Navbar style change according to user level

---

src/component/UserTable/UserTable.js
src/pages/AdminUserPage.js
src/redux/userSlice.js

feature-admin-user-page
- getusersInfo action 추가
- admin user page 추가

feature-admin-user-page

---

src/component/OrderDetailDialog/OrderDetailDialog.js
src/component/UserDetailDialog/UserDetailDialog.js
src/component/UserTable/UserTable.js
src/constants/order.constants.js
src/pages/AdminOrderPage.js
src/pages/AdminUserPage.js
src/redux/userSlice.js
src/style/adminUserPage.style.css

feature admin userpage
- admin user page add

feature admin userpage

---

src/component/UserDetailDialog/UserDetailDialog.js
src/component/UserTable/UserTable.js
src/pages/AdminUserPage.js
src/redux/userSlice.js
src/style/adminUserPage.style.css

feature userslice update delete
- userslice update delete add
- user table add

feature userslice update delete

---

src/Layout/AppLayout.js
src/component/IngredientTable/IngredientTable.js
src/component/NewItemDialog/NewItemDialog.js
src/component/SideBar/sidebar.js
src/constants/ingredient.constants.js
src/pages/AdminIngredientsPage.js
src/pages/AdminOrderPage.js
src/redux/ingredientSlice.js

- Fixed undefined property access in IngredientTable component.
- Updated table cell rendering to safely access properties using optional chaining.
- Ensured smooth submission and error-free rendering of ingredients.

Fix: Resolve issue with ingredient table rendering and submission

---

package-lock.json
package.json
src/Layout/AppLayout.js
src/component/AddressInput/AddressInput.js
src/component/DeliveryEstimate/DeliveryEstimate.js
src/component/RecentlyViewed/RecentlyViewed.js
src/pages/IngredientsDetail.js
src/pages/StorePage.js
src/redux/ingredientSlice.js
src/style/IngredientsDetail.style.css
src/style/addressInput.style.css

design ingredient detail page
- ingredient detail page
- ingredient detail page react-daum-postcode add

44 design ingredient detail page

---

src/App.css
src/component/FridgeItemCard/FridgeItemCard.js
src/component/MyFridgeSearchResults/MyFridgeSearchResults.js
src/component/Navbar/Navbar.js
src/component/Navbar/SearchBox.js
src/component/SearchResultCard/SearchResultCard.js
src/pages/MyFridge.js
src/pages/StorePage.js
src/redux/fridgeSlice.js
src/redux/ingredientSlice.js
src/redux/store.js
src/style/fridgeItemCard.style.css
src/style/myFridge.style.css
src/style/searchResultCard.style.css

feature my fridge page
- Design my fridge page
- fridge create and delete, read

49 feature my fridge page

---

src/component/FridgeItemCard/FridgeItemCard.js
src/component/MyFridgeSearchResults/MyFridgeSearchResults.js
src/pages/MyFridge.js
src/redux/fridgeSlice.js
src/style/fridgeItemCard.style.css
src/style/myFridge.style.css
src/style/searchResultCard.style.css

feature-my-fridge-page-add-recipe

feature-my-fridge-page-add-recipe

---

src/component/MyOrderComponent/MyOrderComponent.js
src/component/MyOrderComponent/MyOrderComponent.style.css
src/component/OrderStatusCard/OrderStatusCard.js
src/component/OrderStatusCard/OrderStatusCard.style.css
src/component/SideBar/SideBar.js
src/pages/CartPage.js
src/pages/OrderCompletePage.js
src/redux/store.js

Add Category Filter and MyOrderComponent
Added category filter functionality for recipes.
Implemented MyOrderComponent to display user orders with pagination.
Enhanced error handling and loading states.
Fixed key prop warning in CartPage.
Included necessary Redux actions and reducers for orders

feat myordercomponet

---

src/component/MyOrderComponent/MyOrderComponent.js
src/component/MyOrderComponent/MyOrderComponent.style.css

fixed orderSelector on myordercomponent . getOrderList to getOrder

fix myordercomponent getOrderlist to getOrder

---

src/component/Review/Review.js
src/component/SearchResultCard/SearchResultCard.js
src/pages/MyFridge.js
src/redux/fridgeSlice.js
src/style/searchResultCard.style.css

Fix fridge page

---

src/component/Category/Category.js
src/component/RecipeAll/RecipeAll.js
src/style/RecipeAll.style.css
src/style/RecipeCard.style.css
src/style/category.style.css

fix-recipe-page

---

src/App.css
src/component/Navbar/Navbar.js
src/component/RecipeAll/RecipeAll.js
src/component/SearchBox/SerachBox.js
src/pages/AdminIngredientsPage.js
src/pages/AdminOrderPage.js
src/pages/AdminRecipePage.js
src/pages/AdminUserPage.js
src/pages/LoginPage.js
src/pages/RecipeDetailPage.js
src/pages/RecipePage.js
src/pages/RegisterPage.js
src/pages/SearchResults.js
src/redux/recipeSlice.js
src/redux/userSlice.js
src/router/AppRouter.js
src/style/LoginPage.style.css

fix-search

---

src/component/Navbar/Navbar.js
src/component/Navbar/Navbar.style.css
src/component/OrderStatusCard/OrderStatusCard.js
src/component/OrderStatusCard/OrderStatusCard.style.css
src/component/UserInfo/UserInfo.style.css

fix-profile

---

src/component/RecipeCard/RecipeCard.js
src/component/Review/Review.js
src/redux/reviewSlice.js

feat review rating

---

src/component/KakaoShareButton/KakaoShareButton.js

fix-kakao-share

---

src/component/Cart/CartItem.js
src/component/MyOrderComponent/MyOrderComponent.js
src/pages/AdminOrderPage.js
src/pages/CartPage.js
src/pages/PaymentPage.js
src/redux/cartSlice.js
src/redux/orderSlice.js

Fix-mypage-orderList-and-cartpage

Fix-mypage-orderList-and-cartpage

---

src/component/MyGroceryNote/MyGroceryNote.js
src/component/ShoppingListDialog/ShoppingListDialog.js
src/pages/OrderCompletePage.js
src/redux/cartSlice.js
src/redux/favoriteSlice.js
src/redux/ingredientSlice.js
src/redux/orderSlice.js
src/redux/shoppingListSlice.js
src/redux/store.js

Feat-grocery-note

---

package-lock.json
package.json
src/Layout/AppLayout.js
src/component/KakaoLogin/KakaoLogin.js
src/component/MyProfileEditComponent/MyProfileEditComponent.js
src/component/Navbar/Navbar.js
src/component/UserInfo/UserInfo.js
src/hooks/useChangePassword.js
src/hooks/useDeleteUser.js
src/hooks/useForgotPassword.js
src/hooks/useGetUsersInfo.js
src/hooks/useLoginUser.js
src/hooks/useLoginWithGoogle.js
src/hooks/useLoginWithKakao.js
src/hooks/useLoginWithToken.js
src/hooks/useRegisterUser.js
src/hooks/useResetPassword.js
src/hooks/useUpdateUser.js
src/hooks/useVerifyCurrentPassword.js
src/index.js
src/pages/AdminUserPage.js
src/pages/ChangePasswordPage.js
src/pages/FindPasswordPage.js
src/pages/LoginPage.js
src/pages/MyProfile.js
src/pages/RegisterPage.js
src/pages/ResetPasswordPage.js
src/pages/VerifyCurrentPassword.js
src/redux/userSlice.js
src/utils/CloudinaryUploadWidget.js

Refactor api request

---

src/component/IngredientCard/IngredientCard.js
src/component/MyOrderComponent/MyOrderComponent.js
src/component/OrderDetailDialog/OrderDetailDialog.js
src/component/RecommendRecipe/RecommendRecipe.js
src/hooks/Ingredient/useEditIngredient.js
src/hooks/Order/useCreateOrder.js
src/hooks/Order/useEditOrder.js
src/hooks/Order/useFetchOrder.js
src/hooks/Order/useFetchOrderList.js
src/hooks/Recipe/useEditRecipe.js
src/hooks/User/useUpdateUser.js
src/pages/AdminOrderPage.js
src/pages/CartPage.js
src/pages/PaymentPage.js
src/redux/orderSlice.js
src/redux/userSlice.js

Refactor order api request

---

src/component/Cart/CartItem.js
src/component/IngredientCard/IngredientCard.js
src/component/SearchResultCard/SearchResultCard.js
src/hooks/Cart/useAddToCart.js
src/hooks/Cart/useDeleteCartItem.js
src/hooks/Cart/useDeleteSelectedCartItems.js
src/hooks/Cart/useEditCartItem.js
src/hooks/Cart/useFetchCart.js
src/pages/AdminIngredientsPage.js
src/pages/AdminOrderPage.js
src/pages/AdminRecipePage.js
src/pages/AdminUserPage.js
src/pages/CartPage.js
src/pages/IngredientsDetail.js
src/pages/MyFridge.js
src/pages/PaymentPage.js
src/redux/cartSlice.js

Refactor-cart-api-request

---

src/component/FridgeItemCard/FridgeItemCard.js
src/component/MyFridgeSearchResults/MyFridgeSearchResults.js
src/component/RecipeCard/RecipeCard.js
src/component/SearchResultCard/SearchResultCard.js
src/hooks/Cart/useFetchCart.js
src/hooks/Fridge/useAddIngredientToFridge.js
src/hooks/Fridge/useDeleteFridgeItem.js
src/hooks/Fridge/useFetchFridgeItems.js
src/hooks/Fridge/useFetchRecommendedRecipes.js
src/hooks/Fridge/useFridgeIngredientRecipeResult.js
src/hooks/Order/useFetchOrder.js
src/hooks/Order/useFetchOrderList.js
src/hooks/Recipe/useFetchIngredients.js
src/hooks/Recipe/useFetchRecipeById.js
src/hooks/Recipe/useFetchRecipes.js
src/hooks/User/useChangePassword.js
src/hooks/User/useDeleteUser.js
src/hooks/User/useForgotPassword.js
src/pages/MyFridge.js
src/redux/fridgeSlice.js
src/utils/CloudinaryUploadWidget.js

Refactor-fridge-api-request

---

src/component/Cart/CartItem.js
src/component/MyGroceryNote/MyGroceryNote.js
src/component/ShoppingListDialog/ShoppingListDialog.js
src/hooks/ShoppingList/useAddToShoppingList.js
src/hooks/ShoppingList/useFetchShoppingList.js
src/hooks/ShoppingList/useMoveToCompletedList.js
src/hooks/ShoppingList/useRemoveFromShoppingList.js
src/pages/CartPage.js
src/pages/IngredientsDetail.js
src/redux/shoppingListSlice.js

Refactor-shoppingList-api-request

Refactor-shoppingList-api-request

---

src/pages/StorePage.js

optimization

---

src/hooks/Cart/useFetchCart.js
src/hooks/Fridge/useFetchRecommendedRecipes.js
src/hooks/Order/useFetchOrder.js
src/hooks/Order/useFetchOrderList.js
src/hooks/Recipe/useFetchRecipeById.js
src/hooks/Recipe/useFetchRecipes.js
src/hooks/ShoppingList/useFetchShoppingList.js
src/index.js

fix: Update query hooks : 쿼리 훅의 cacheTime -> gcTime 으로변경

fix: Update query hooks

---

src/component/Navbar/Navbar.tsx
src/pages/MyFridge.tsx
src/pages/SearchResults.tsx

Myfridge err

---

src/component/IngredientAll/IngredientAll.tsx

스토어 페이지에서 더보기 버튼을 눌러야 새로운 데이터를 불러오던 방식에서
새로운 데이터 불러오는 방식을 무한 스크롤의 형태로 변경

feat : ingredients data infiniteScrolling

---

src/component/CopyClipButton/CopyClipButton.tsx

copy clip button component url 수정

fix : copy clip button component url

---

src/component/RecommendRecipe/RecommendRecipe.tsx

recommend recipe component 4번째 이미지 width, height 조정

fix : recommend recipe component

---

src/Layout/AppLayout.tsx
src/component/IngredientDialog/IngredientDialog.tsx
src/component/IngredientSlider/IngredientSlider.tsx
src/component/KakaoShareButton/KakaoShareButton.tsx
src/component/Navbar/Navbar.tsx
src/component/RecipeCard/RecipeCard.tsx
src/component/RecipeCategory/RecipeCategory.tsx
src/component/RecipeForm/RecipeForm.tsx
src/component/RecipeSlider/RecipeSlider.tsx
src/component/RecommendRecipe/RecommendRecipe.tsx
src/component/RecommendRecipe/RecommendRecipeCard.tsx
src/component/ShoppingListDialog/ShoppingListDialog.tsx
src/component/Skeleton/CartPageSkeleton.tsx
src/component/Skeleton/RecipeCardSkeleton.tsx
src/component/Skeleton/RecipeDetailSkeleton.tsx
src/component/Skeleton/RecommendRecipeSkeleton.tsx
src/component/SubBanner/SubBanner.tsx
src/constants/responsive.tsx
src/pages/CartPage.tsx
src/pages/LoginPage.tsx
src/pages/MainPage.tsx
src/pages/MyFridge.tsx
src/pages/MyRecipePage.tsx
src/pages/RecipeDetailPage.tsx
src/pages/RegisterPage.tsx
src/pages/StorePage.tsx
src/types.ts

Recipepage tailwind migrate

---

src/component/DateFilterCondition/DateFilterCondition.jsx
src/component/MyGroceryNote/MyGroceryNote.tsx
src/component/MyOrderComponent/MyOrderComponent.tsx
src/component/MyPageOrderDialog/MyPageOrderDialog.tsx
src/component/MyProfileEditComponent/MyProfileEditComponent.tsx
src/component/MyRecipeComponent/MyRecipeComponent.tsx
src/component/UserInfo/UserInfo.tsx
src/pages/ChangePasswordPage.tsx
src/pages/FindPasswordPage.tsx
src/pages/LoginPage.tsx
src/pages/RegisterPage.tsx
src/pages/VerifyCurrentPassword.tsx
src/redux/userSlice.tsx

feat : MyProfile Page and related components tailwind css migrate

feat : MyProfile Page and related components tailwind css migrate

---

src/Layout/AppLayout.tsx
src/component/AdminDashboard/AdminDashboardCard.tsx
src/component/DashBoardCard/DashboardCard.tsx
src/component/DateFilterCondition/DateFilterCondition.jsx
src/component/IngredientCard/IngredientCard.tsx
src/component/IngredientTable/IngredientTable.tsx
src/component/MyOrderComponent/MyOrderComponent.tsx
src/component/NewItemDialog/NewItemDialog.tsx
src/component/OrderDetailDialog/OrderDetailDialog.tsx
src/component/OrderTable/OrderTable.tsx
src/component/RecipeCategory/RecipeCategory.tsx
src/component/RecipeForm/RecipeForm.tsx
src/component/RecipeTable/RecipeTable.tsx
src/component/SideBar/SideBar.tsx
src/component/UserDetailDialog/UserDetailDialog.tsx
src/component/UserTable/UserTable.tsx
src/hooks/Cart/useDeleteCartItem.tsx
src/pages/AdminDashBoardPage.tsx
src/pages/AdminIngredientsPage.tsx
src/pages/AdminOrderPage.tsx
src/pages/AdminRecipePage.tsx
src/pages/AdminUserPage.tsx
src/pages/CartPage.tsx
src/pages/LoginPage.tsx
src/pages/MyProfile.tsx
src/pages/NotFoundPage.tsx
src/pages/OrderCompletePage.tsx
src/pages/RecipeDetailPage.tsx
src/pages/ResetPasswordPage.tsx
src/pages/SearchResults.tsx

Tailwind css migrate
